[package]
name = "axplat-aarch64-peripherals"
version = "0.1.1"
description = "ARM64 common peripheral drivers with `axplat` compatibility"
documentation = "https://docs.rs/axplat-aarch64-peripherals"
keywords = ["arceos", "os", "hal", "peripheral", "aarch64"]
categories = ["embedded", "no-std", "hardware-support", "os"]
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kspin = "0.1"
log = "0.4"
int_ratio = "0.1"
lazyinit = "0.2"
page_table_entry = "0.5"
aarch64-cpu = "10.0"
arm_pl011 = "0.1"
# wait for the PR merged and released on crates.io, modify this to arm_gicv2 = "0.2"
arm_gicv2 = { git = "https://github.com/arceos-hypervisor/arm_gicv2", branch = "ipi" }
arm_pl031 = "0.2"
axcpu = { workspace = true }
axplat = { workspace = true, features = ["irq"] }

[package.metadata.docs.rs]
targets = ["aarch64-unknown-none"]
